create extension if not exists vector with schema extensions;

create table if not exists public.rag_chunks (
  id text primary key,
  character text not null,
  source text not null,
  chunk_index integer not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(2048) not null,
  created_at timestamptz not null default now()
);

create index if not exists rag_chunks_character_idx
  on public.rag_chunks (character);

create index if not exists rag_chunks_embedding_hnsw_idx
  on public.rag_chunks
  using hnsw (embedding vector_cosine_ops);

create or replace function public.match_rag_chunks(
  query_embedding vector(2048),
  match_count integer default 5,
  character_filter text default 'napoleon'
)
returns table (
  id text,
  content text,
  source text,
  metadata jsonb,
  distance double precision
)
language sql
stable
as $$
  select
    rag_chunks.id,
    rag_chunks.content,
    rag_chunks.source,
    rag_chunks.metadata,
    rag_chunks.embedding <=> query_embedding as distance
  from public.rag_chunks
  where rag_chunks.character = character_filter
  order by rag_chunks.embedding <=> query_embedding
  limit match_count;
$$;

create table if not exists public.editorial_dossiers (
  id bigint generated by default as identity primary key,
  day date not null,
  character_id text not null default 'napoleon',
  question text not null,
  origin text not null default 'manual',
  dossier text not null,
  angle text not null default '',
  sources jsonb not null default '[]'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (day, character_id, question)
);

create index if not exists editorial_dossiers_day_idx
  on public.editorial_dossiers (day desc);

create index if not exists editorial_dossiers_character_idx
  on public.editorial_dossiers (character_id);
